name: Build App with Custom Service

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL for the API'
        required: true
        default: 'https://rickandmortyapi.com/api/'
      service_name:
        description: 'Name of the service (e.g., RickAndMorty, AnotherService)'
        required: true
        default: 'RickAndMorty'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: Debug environment
      run: |
        dart --version
        flutter --version
        flutter doctor

    - name: Install dependencies
      run: flutter pub get

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Initialize Flutter
      run: flutter precache

    - name: Setup Flutter stable channel
      run: |
        flutter channel stable
        flutter upgrade

    - name: Validate Flutter installation
      run: flutter doctor

    - name: Build APK
      run: |
        flutter pub get
        flutter build apk \
          --dart-define=BASE_URL=${{ github.event.inputs.base_url }} \
          --dart-define=SERVICE_NAME=${{ github.event.inputs.service_name }}

    - name: Verify Build
      run: echo "Build successful"